### ISSUE TITLE
TypeError: Cannot read property 'return' of undefined

### ISSUE THREAD

**Issue by test2015deve** [eris-ltd/eris#1236]
**_Im getting this error. Could you help me to solve this?_** 

/root/.eris/apps/idi/node_modules/eris-contracts/lib/pipes/dev_pipe.js:98
                callback(null, data.return);
                                   ^

TypeError: Cannot read property 'return' of undefined
    at /root/.eris/apps/idi/node_modules/eris-contracts/lib/pipes/dev_pipe.js:98:36
    at /root/.eris/apps/idi/node_modules/eris-db/lib/transactions.js:176:9
    at fixedCallback (/root/.eris/apps/idi/node_modules/eris-db/lib/unsafe.js:120:13)
    at /root/.eris/apps/idi/node_modules/eris-db/lib/rpc/http.js:81:13
    at httpRequest.onreadystatechange (/root/.eris/apps/idi/node_modules/eris-db/lib/rpc/http.js:103:17)
    at dispatchEvent (/root/.eris/apps/idi/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:572:25)
    at setState (/root/.eris/apps/idi/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:14)
    at IncomingMessage.<anonymous> (/root/.eris/apps/idi/node_modules/eris-db/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:431:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

**Comment by VoR0220** [comment]
This is an issue that should be filed in eris-contracts.js. Closing.
